<?php

namespace ObjectBundle\Repository;

/**
 * CraftingRecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CraftingRecipeRepository extends \Doctrine\ORM\EntityRepository
{
}
