<?php

namespace ObjectBundle\Repository;

/**
 * WeaponAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeaponAttachmentRepository extends \Doctrine\ORM\EntityRepository
{
}
