<?php

namespace ObjectBundle\Repository;

/**
 * WeaponTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeaponTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
