<?php

namespace PlayerBundle\Repository;

/**
 * SkillTreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillTreeLevelRepository extends \Doctrine\ORM\EntityRepository
{
}
