<?php

namespace PlayerBundle\Repository;

/**
 * TraitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraitsRepository extends \Doctrine\ORM\EntityRepository
{
}
