<?php

namespace ServiceBundle\Repository;

/**
 * WSCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WSCRepository extends \Doctrine\ORM\EntityRepository
{
}
